{% set name = "openmetadata-ingestion" %}
{% set version = "0.13.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openmetadata-ingestion-{{ version }}.tar.gz
  sha256: 84f95b667136d04d482e0b350e8707c6b6bd294b80191eecef4a54599640feac

build:
#  entry_points:
#    - metadata = metadata.cmd:metadata
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - commonregex
    - jsonschema
    - boto3 >=1.19.12
    - python-jose >=3.3.0
    - croniter >=1.3.0
    - importlib-metadata >=4.11.0
    - typing_inspect
    - botocore >=1.22.12
    - requests-aws4auth >=1.1.1
    - email-validator >=1.0.3
    - idna >=2.5
    - google-auth >=1.33.0
    - jinja2 >=2.11.3
    - wheel >=0.36.2
    - pyyaml
    - cryptography
    - sqlalchemy >=1.4.0
    - sqllineage >=1.3.7
    - python-dateutil >=2.8.1
    - typing-compat >=0.1.0
    - googlesearch >=3.0.0
    - mypy_extensions >=0.4.3
    - antlr4-python3-runtime >=4.9.2
    - pydantic >=1.9.0
    - pymysql >=1.0.2
    - requests >=2.23
# Rerender
    - grpcio-tools >=1.48.2
    - cached-property >=1.5.2
    - avro-python3 >=1.10.2
    - chardet >=4.0.0
    - pandas >=1.3.5

test:
  imports:
    - metadata

about:
  home: https://open-metadata.org/
  summary: Ingestion Framework for OpenMetadata
  dev_url: https://github.com/open-metadata/OpenMetadata
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
