{% set name = "openmetadata-ingestion" %}
{% set version = "1.1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openmetadata-ingestion-{{ version }}.tar.gz
  sha256: 682126523db69f4ce3b930b551df7295c8ee3655319fc73e3417afac82ea7af0

build:
#  entry_points:
#    - metadata = metadata.cmd:metadata
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pydantic >=1.10,<2.0
    - sqlalchemy >=1.4.0,<2
    - cached-property >=1.5.2
    - memory_profiler
    - googlesearch >=3.0.0
    - chardet >=4.0.0
    - boto3 >=1.20,<2.0
    - importlib-metadata >=4.13.0,<7.0.0
    - croniter >=1.3.0,<1.5.0
#    - antlr4-python3-runtime ==4.9.2 # Causes run time issues with Python 37 use newer feedstock
#      https://github.com/conda-forge/antlr-python-runtime-feedstock/blob/main/recipe/meta.yaml
    - antlr-python-runtime >=4.7.2
    - pyyaml
    - idna >=2.5,<4
    - setuptools >=66.0.0,<69.0.0
    - jsonschema
    - typing-compat >=0.1.0,<0.2.0
    - openmetadata-sqllineage >=1.0.4
    - email-validator >=1.0.3
    - google-auth >=1.33.0
    - commonregex
    - pymysql >=1.0.2
    - typing-extensions <=4.8.0
    - wheel >=0.38.4,<0.42.0
    - requests >=2.23
    - python-dateutil >=2.8.1
    - jinja2 >=2.11.3
    - tabulate >=0.9.0
    - cryptography
    - mypy_extensions >=0.4.3
    - requests-aws4auth >=1.1,<2.0
#    - grpcio-tools >=1.47.2 # Causes run time issues with Python 37
    - avro-python3 >=1.10.2,<2.0 # avro >=1.11,<2.0 # causes both pip check and metadata --help to fail
    - jsonpatch >=1.32
    - typing_inspect
    - python-jose >=3.3,<4.0

test:
  imports:
    - airflow_provider_openmetadata
    - metadata

about:
  home: https://open-metadata.org/
  summary: Ingestion Framework for OpenMetadata
  dev_url: https://github.com/open-metadata/OpenMetadata
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
