{% set name = "openmetadata-ingestion" %}
{% set version = "1.1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openmetadata-ingestion-{{ version }}.tar.gz
  sha256: 3f63f93e46ceda3ac47665e4e992e92a4b085c68d6982c5bdacda05f91618728

build:
  entry_points:
    - metadata = metadata.cmd:metadata
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - openmetadata-sqllineage >=1.0.4
    - typing_inspect
    - typing-extensions
    - setuptools >=66.0.0
    - requests-aws4auth >=1.1,<2.0
    - importlib-metadata >=4.13.0
    - wheel >=0.38.4
    - jsonschema
    - chardet >=4.0.0
    - cryptography
    - pymysql >=1.0.2
    - pyyaml
    - grpcio-tools >=1.47.2 # Causes run time issues with Python 37
    - avro-python3 >=1.10.2,<2.0 # avro >=1.11,<2.0 # causes both pip check and metadata --help to fail
    - fastavro
    - jsonpatch >=1.32
    - requests >=2.23
    - python-jose >=3.3,<4.0
    - cached-property >=1.5.2
    - email-validator >=1.0.3
    - sqlalchemy >=1.4.0,<2
    - typing-compat >=0.1.0
    - idna >=2.5
    - jinja2 >=2.11.3
    - memory_profiler
    - antlr4-python3-runtime >=4.9.2 # Causes run time issues with Python 37 use newer feedstock
#      https://github.com/conda-forge/antlr-python-runtime-feedstock/blob/main/recipe/meta.yaml
#    - antlr-python-runtime >=4.7.2
    - googlesearch >=3.0.0
    - mypy_extensions >=0.4.3
    - google-auth >=1.33.0
    - commonregex
    - croniter >=1.3.0
    - python-dateutil >=2.8.1
    - tabulate ==0.9.0
    - pydantic >=1.10,<2.0
    - boto3 >=1.20,<2.0

test:
  imports:
    - airflow_provider_openmetadata
    - metadata
  commands:
    #- pip check # openmetadata-ingestion 1.1.1.1 requires avro, which is not installed.
    #- metadata --help # ModuleNotFoundError: No module named 'avro.errors'
  requires:
    - pip

about:
  home: https://open-metadata.org/
  summary: Ingestion Framework for OpenMetadata
  dev_url: https://github.com/open-metadata/OpenMetadata
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
