{% set name = "openmetadata-ingestion" %}
{% set version = "1.8.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c1fbb4bbfb9f79ba55e7233572ff6ded12e3af060065688d0441dea9d33176f9

build:
  entry_points:
    - metadata = metadata.cmd:metadata
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - shapely
    - requests-aws4auth >=1.1,<2.0
    - collate-sqllineage >=1.6.0,<1.7.0
    - memory_profiler
    - cached-property >=1.5.2
    - azure-keyvault-secrets
    - pyyaml >=6.0,<7.0
    - google-cloud-secret-manager >=2.22.1
    - cryptography >=42.0.0
    - jaraco.functools <4.2.0
    - chardet >=4.0.0
    - google-crc32c
    - python-dateutil >=2.8.1
    - mysql-connector-python >=9.1
    - jinja2 >=2.11.3
    - antlr4-python3-runtime >=4.9.2
    - jsonpatch >=1.24,<2.0
    #- collate-data-diff
    - boto3 >=1.20,<2.0
    - python-dotenv >=0.19.0
    - tabulate >=0.9.0
    - requests >=2.23
    - packaging
    - typing_inspect
    - snowflake-connector-python >=3.13.1,<4.0.0
    - setuptools >=70.0,<71.0
    - mypy_extensions >=0.4.3
    - pydantic-settings >=2.7.0,<3.0
    - importlib-metadata >=4.13.0
    - email-validator >=2.0
    - sqlalchemy >=1.4.0,<2.0
    - pydantic >=2.7.0,<3.0
    - pymysql >=1.0,<2.0
    - azure-identity >=1.12,<2.0

test:
  imports:
    - airflow_provider_openmetadata
    - metadata
  commands:
    #- metadata --help re.error: global flags not at the start of the expression at position 1
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://open-metadata.org/
  summary: Ingestion Framework for OpenMetadata
  dev_url: https://github.com/open-metadata/OpenMetadata
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
